changelog:
  categories:
    - title: Features
      labels:
        - feat
        - feature
    - title: Fixes
      labels:
        - fix
        - bug
    - title: Documentation
      labels:
        - docs
    - title: Maintenance
      labels:
        - chore
        - ci
        - refactor
    - title: Other Changes
      labels:
        - '*'
